<div class="log-item" id="m16">
    <div class="log-inner">
        <div class="log-head clearfix">
            <div class="pull-right"><span class="label label-default"><?=$this->commit->getRepository()->url?></span></div>
            <div class="avatar pull-left"><a href="<?=$this->url('log', ['author' => $this->commit->commit_author])?>"><img src="https://sigil.cupcake.io/<?=$this->commit->commit_author?>"></a></div>
            <div class="user-detail">
                <h5 class="handle"><?= substr($this->commit->commit_message, 0, 64)?><?=(strlen($this->commit->commit_message) > 64 ? '&#8230;' : '')?></h5>
                <div class="post-meta">
                    <div class="asker-meta">
                        <span class="log-what"></span>
                            <span class="log-when">
                                <span class="log-when-data"><?= (new DateTime($this->commit->commit_date, new DateTimeZone('UTC')))->format('Y-m-d g:i a e')?></span>
                            </span>
                            <span class="log-who">
                                <span class="log-who-pad">by </span>
                                <span class="log-who-data"><a href="<?=$this->url('log', ['author' => $this->commit->commit_author]);?>"><?= $this->commit->commit_author?></a></span>
                            </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="log-content">
            <?=$this->markdown($this->commit->commit_message)?>
            <?php foreach($this->commit->getCommitFileStatuses() as $fileStatus){?>
                <?=$this->partial('partial/file-status.phtml', ['fileStatus' => $fileStatus])?>
            <?php } ?>
        </div>
    </div>
</div>