<div class="row">
    <h2>Commit Log</h2>
</div>
<div class="commit-log-list" id="commit-log">

    <?php
    use Application\Model\Commit;

    /** @var Commit $commit */
    foreach($this->items as $commit){?>

    <?= $this->partial('partial/commit.phtml', ['commit' => $commit])?>

    <?php } ?>
</div>




<?php echo $this->paginationControl($this->items,
    'Sliding',
    'partial/pagination.phtml',
    ['route' => 'log']); ?>
